# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1725c957db5fced9575677d874ea8b96ee1567d9998981d3f3019f03a4e8ffb5223e68fe16795e2c9ad45fbab01ea3f64537d02135ed209ef3a9c9a1795b45b7

test:
  secret_key_base: e2b8d6d30c1ff71d8284b68227693563badd5ccbbffffe91adf618773e2f3f7b6ec180cce176866f4f68ffaa275b8fc69a3ba3fe8545c601d94462a559d73fa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
